# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Run the LIVE development server using `bundle exec jekyll serve -o -l`

#### TOC - [ctrl] + [f] to find these sections in the config.
# - Site Settings, Meta, and SEO
# - Search
# - CommentBox
# - Contact Form
# - Build Settings

#### Site Settings, Meta, and SEO
title: JLSunday
email: admin@jlsunday.com
description: >- # this means to ignore newlines
  Programming and web development tutorials, snippets, and other resources for C#, Python, Angular, Docker, SQL, Azure and more!
tagline: Programming and web development tutorials, snippets, and other resources.
google_site_verification: ''
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jlsunday.com" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Justin L. Sunday
  url: https://JLSunday.com/
default_locale: "en"
logo_light: "/assets/images/JLSunday-logo/JLSunday-no-background.png"
logo_dark: "/assets/images/JLSunday-logo/JLSunday-no-background.png"
show_contact_info: true # Personal Info (twitter,GitHub,email) can be seen in `\_includes\sidebar\aboutme.html`, this info only shown where show_contact_info == true
include_blogroll: true
feed:
  excerpt_only: true
footer: # Optional links for sitemap, privacy policy, cookie policy, and terms of service. These have placeholders inside that specify the author's/website's names. So, if you are in the United States, theis should be pretty much plug and play. I would definitely recommend that you look these over yourself for safety reasons. I assume no responsibility if you use these provided files. They are meant as placeholders/ templates to be edited for your specific use-case.
  include_sitemap: true
  include_privacypolicy: true
  include_cookiepolicy: true
  include_terms: true
aboutme:
  include: true
  text: >-
    Hello, my name is Justin! I live in the US with my wife, amazing daughters, and our crazy canines. 
    I'm extremely passionate about software development, programming, absorbing every bit of knowledge
    I can, and sharing that knowledge with anyone interested in learning.
  photo:
    use_github_avatar: false
    asset_path: "/assets/images/author/profile-photo-1352x1098.png" # "/path/to/profile-photo.png"
    hosted_aboutme_photo: # "https://github.com/sundayj/sundayj.github.io/blob/master/assets/images/author/profile-photo-1352x1098.png?raw=true" # Use if you want to use a photo from somewhere else on the web
google_analytics_key: "G-4Z30BJZ3LK" # UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)

#### Search
# If you would like to include algolia search in your site, please refer to this blog post by Algolia: https://www.algolia.com/blog/engineering/instant-search-blog-documentation-jekyll-plugin/
algolia:
  application_id: NOSLLDLG24
  index_name: posts
  search_only_api_key: 446836c037be07a8fff66ade8d708aee
  files_to_exclude:
    - pages/home.md
    - pages/about.md
    - pages/archives.md
    - pages/categories.md
    - pages/tags.md
    - pages/search.md
  settings:
    attributesToHighlight:
      - categories
      - content
      - headings
      - html
      - tags
      - title
    attributesToSnippet:
      - content:10
      - summary:10

#### CommentBox
comment_box: 5706851450617856-proj # project Id

#### Contact Form
fab_form: Aj7sjuE # form Id

### Build Settings
# Kramdown Configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
paginate: 5
excerpt_separator: <!-- more -->
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-seo
  - jekyll-remote-theme
  #  - jekyll-sitemap

remote_theme: sundayj/DevSculptor
