name: algolia-search

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  algolia-search:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Update Algolia search index
        uses: dieghernan/algolia-jekyll-action@37e24cce44f139a20726bbb37f3e4df00109a17b # v1
        with:
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
